#!/bin/bash
clear

for i in {0..12}
do
  make test$i &> /dev/null #ensure all test cases are run
done

read -rp "Enter a filename for the output to be sent to: " file

clear

read -p "Press any key to display int outputs"

clear

for i in {0..12}
do
  if diff "./expected/intexpected$i" "./outputs/intoutput$i"; then
    echo "Int $i output is correct" | tee -a $file
  else
    echo "Int $i output is incorrect" | tee -a $file
  fi

  memory=`cat ./outputs/intmem* | grep errors | awk 'BEGIN { sum = 0 } { sum += $4 } END { print sum }'`

  echo "There are $memory memory errors in int $i" | tee -a $file

  printf "\n"
done

printf "\n\n"

read -p "Press any key to display str outputs"
clear

for i in {0..9}
do
  if diff "./expected/strexpected$i" "./outputs/stroutput$i"; then
    echo "Str $i output is correct" | tee -a $file
  else
    echo "Str $i output is incorect" | tee -a $file
  fi

  memory=`cat ./outputs/strmem* | grep errors | awk 'BEGIN { sum = 0 } { sum += $4 } END { print sum }'`

  echo "There are $memory memory errors in str $i" | tee -a $file
   printf "\n"
done
